version: "3"

services:

    web:
        container_name: {{ cookiecutter.project_slug }}_web
        build:
            context: ./web
            dockerfile: dockerfile
        volumes:
            - ./web:/web
        ports:
            - "3000"
    {%- if cookiecutter.cloud_database == "n" -%}
    mongo:
        container_name: {{ cookiecutter.project_slug }}_database
        image: mongo
        restart: always
        ports:
            - "27017"
        environment:
            {% if cookiecutter.mongodb_user != "" %}
            MONGO_INITDB_ROOT_USERNAME: {{ cookiecutter.mongodb_user }}
            {%- elif cookiecutter.mongodb_user == "" -%}
            MONGO_INITDB_ROOT_USERNAME: root
            {% endif %}
            {%- if cookiecutter.mongodb_user != "" -%}
            MONGO_INITDB_ROOT_USERNAME: {{ cookiecutter.mongodb_password }}
            {%- elif cookiecutter.mongodb_user == "" -%}
            MONGO_INITDB_ROOT_PASSWORD: password
            {%- endif -%}
    {% endif %}

    api:
        container_name: {{ cookiecutter.project_slug }}_api
        build:
            context: ./api
        ports:
            - "8000"
        volumes: 
            - ./api:/usr/src/api
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DB_URI: ${DB_URI}

    nginx:
        container_name: {{ cookiecutter.project_slug }}_proxy
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - web
            - api
