version: "3"

services:
    web:
        container_name: {{ cookiecutter.project_slug }}_web
        build:
            context: ./web
            dockerfile: dockerfile
        volumes:
            - ./web:/web
        ports:
            - "3000"
    nginx:
        container_name: {{ cookiecutter.project_slug }}_proxy
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - web
