FROM python:3.8-alpine

RUN mkdir /api
WORKDIR /api

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD uvicorn main:api --root-path /api --host 0.0.0.0 --port 8000
